id: P000496
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21945
  title: བཞད་གད་ཀྱི་གཏམ།
  author: ''
  volumes:
    2267e2a43f604f08ab87f714e4fca80f:
      image_group_id: I1KG23328
      title: Volume 1 of bzhad gad kyi gtam/
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
